name: Daily Patrolling Bot

on:
  schedule:
    - cron: '0 0 * * *'   # daily at midnight UTC
  workflow_dispatch:      # manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Pywikibot
        run: pip install pywikibot

      - name: Run bot script
        env:
          PYWIKIBOT_USER: ${{ secrets.PYWIKIBOT_USER }}
          PYWIKIBOT_PASSWORD: ${{ secrets.PYWIKIBOT_PASSWORD }}
        run: python bot.py
